# Task 4a: docker-compose.yml file to run tests for both backend and frontend
# Assumptions:
# - To keep the backend container small, whisper model is mocked in unit tests.
# - Docker containers are used for testing as it is assumed that reviewer have a docker setup to run the production code.
#   - This will avoid verbose Windows PowerShell or Linux bash scripts to setup the environment for testing.
services:
  backend_test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - AUDIO_STORAGE_PATH=audio_storage
    volumes:
      - data_test:/app/data

  frontend_test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - JEST_SILENT=true  # Set this to 'true' to silence Jest output

volumes:
  data_test: