services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=sqlite:///./data/transcriptions.db
      - AUDIO_STORAGE_PATH=audio_storage
      - WHISPER_MODEL=tiny
      # Setting Timezone
      - TZ=Asia/Singapore
    volumes:
      - data:/app/data
      - audio_storage:/app/audio_storage
    networks:
      - app-network
    healthcheck:
      # Credits: https://github.com/dart-lang/dart-docker/issues/58#issuecomment-1086975460
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9090' || exit 1
      interval: 5s
      timeout: 2s
      retries: 3

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    # Ensure backend service is available before starting frontend
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  data:
  audio_storage:

networks:
  app-network:
    driver: bridge