services:
  backend:
    build:
      context: ./backend
    environment:
      # Ensure DATABASE_URL and AUDIO_STORAGE_PATH are set appropriately
      - DATABASE_URL=sqlite:///./data/transcriptions.db
      - AUDIO_STORAGE_PATH=audio_storage
    volumes:
      - data:/app/data
      - audio_storage:/app/audio_storage
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    # Ensure backend service is available before starting frontend
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  data:
  audio_storage:

networks:
  app-network:
    driver: bridge