# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["ALL"]
ignore = [
    #### modules
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "C90", # mccabe complexity
    "DJ",  # django
    "EXE", # flake8-executable
    "T10", # debugger
    "TID", # flake8-tidy-imports
    "PTH", # Path POSIX

    #### specific and recommended ignores
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D213",
    "D300",
    "D400",
    "D401",
    "D415",
    "E111",
    "E114",
    "E117",
    "E402",   # false positives for local imports
    "E501",   # line too long
    "ISC001",
    "ISC002",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "TRY002", # custom exceptions
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "W191",

    #### project specific
    "FIX002",   # too verbose descriptions of todos
    "S104",     # bind all interfaces
    "BLE",      # Catch all exceptions
    "FBT",      # boolean positional fine for API
    "G004",     # allow fstrings in logging
    "B008",     # Depends keyword for FastAPI
    "FAST002",  # requiring Annotated keyword
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[lint.per-file-ignores]
# Ignore all directories named `tests`.
"tests/**" = [
    "INP001",
    "S101",    # Asserts 
    "ERA001",  # Comments
    "PLR2004", # Magic Values
]
